version: "3"

services:
  parcels-n-at:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/parcels-n-at/Dockerfile
    restart: always
    ports:
      - "3033:3000"
  website:
    container_name: website
    build:
      context: .
      dockerfile: ./apps/website/Dockerfile
    restart: always
    ports:
      - "3000:3000"
