import "./globals.css";
import "ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { ButtonProps } from "../components/button.ts";
import { Button } from "../components/button.ts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.JSX.Element {
  const props: ButtonProps = {};
  return (
    <html lang="en">
      <body className={inter.className}>
        {children} <Button {...props}>Hello</Button>
      </body>
    </html>
  );
}
